### ISSUE TITLE
Alert the user that the list next to a map shows only languages visible in the current view of the map

### ISSUE THREAD

**Issue by MariAnShum** [Jazyki-Mira/langworld_db_pyramid#167]
While viewing a map, to a new user is not immediately obvious that the list next to it contains only the languages displayed at the currently visible map fragment. Perhaps we should explicitly let the users know about it.

VG also writes:
> Сейчас при увеличении карты в списке остаются только те признаки, которые на ней остаются видны. Интуитивно ли это? Я не сразу догадался, куда все делось.

**Comment by lemontree210** [comment]
fixed by #240
